default: &default

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: joobs
  pool: 5
  timeout: 5000

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: joobs_test
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: db/production.sqlite3
